### ISSUE TITLE
How can I split 'commands'?

### ISSUE THREAD

**Issue by vizakenjack** [lubien/elixir-telegram-bot-boilerplate#1]
Hello. Thanks for your project, I write telegram bot and it's really very handy.

I have a question - if my `commands.ex` file gets too big, how can I split it? I have tried to create a new file, with `use Commander` and then import it to `commands`, but it doesn't work. It works when I add it to Matcher like this:
```
def handle_cast(message, state) do
  Commands.match_message message
  SomeOtherCommands.match_message message

  {:noreply, state}
end
```

But I don't like it, because it shows warnings if it can't match a command.

Is there another way to do it?

**Comment by lubien** [comment]
Thanks for pointing it out.

Currently there's no decent way to split commands across files. With that in mind I'll be prototyping few updates here.

I think I'll be doing something like [elixir-lang/plug](/elixir-lang/plug):

```elixir
defmodule App.Commands do
  use App.Commander
  alias App.Commands.UserCommands

  command "foo" do
    # foo command code
  end

  forward "add-user", UserCommands, :add
end
```

That way you can have a centralized command list at `App.Commands` and a `/lib/app/commands/` folder to properly separate code modules.

Give me some time :)
