### ISSUE TITLE
`protocol String.Chars not implemented for {:option, :server_only, :honor_cipher_order}` on startup

### ISSUE THREAD

**Issue by samm81** [lubien/elixir-telegram-bot-boilerplate#20]
Hi,

Just tried to get started with this repository. After setting up my `config.exs` I ran `mix` and received the following error:

```elixir
17:21:00.712 [error] GenServer App.Poller terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:option, :server_only, :honor_cipher_order} of type Tuple. This protocol is implemented for the following type(s): NaiveDateTime, BitString,
 Atom, Integer, Version.Requirement, Date, Version, Float, URI, DateTime, Time, List
    (elixir 1.10.2) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.10.2) lib/string/chars.ex:22: String.Chars.to_string/1
    (logger 1.10.2) lib/logger.ex:792: Logger.__do_log__/3
    (app 0.1.0) lib/app/poller.ex:52: App.Poller.process_messages/1
    (app 0.1.0) lib/app/poller.ex:20: App.Poller.handle_cast/2
    (stdlib 3.10) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.10) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :update}
State: 0
```

This can be fixed by wrapping `reason` in `inspect` on line 52: `Logger.log(:error, inspect(reason))`.

With that in place, starting the server causes it to spit out endless messages:

```elixir
[error] {:option, :server_only, :honor_cipher_order}
```

This happens because a call to `Nadia.get_updates` (or any `Nadia` function) returns

```elixir
{:error,
 %Nadia.Model.Error{reason: {:option, :server_only, :honor_cipher_order}}}
```

This seems to come from an issue with using the older version of hackney that `Nadia` 0.4.1 uses on OTP 22.1 or higher (I am using OTP 22).

This can be safely fixed by upgrading `Nadia`: `{:nadia, "~> 0.6.0"}`.
Additionally, since `Nadia` drops `:poison` as a dependency and this project was implicitly relying on it (poller.ex:70, poller.ex:17, poller.ex:18) you have to manually add it as a dependency (`{:poison, "~> 3.1}`).

This was all tested on Erlang/OTP 22, Elixir 1.10.2, and Ubuntu 18.04.4 LTS.

**Comment by lubien** [comment]
Many thanks!
